module.exports.sampleData = [
  {
    title: "Starlit Reverie - A Celestial Dream",
    description:
      "A mesmerizing close-up of a girl with long, pastel-colored hair, gazing at the starry sky with wonder. Glowing constellations reflect in her deep, enchanting eyes, as strands of her hair seem to blend into the cosmic expanse, embodying a celestial dream.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354155/Default_Closeup_of_a_melancholic_girl_with_flowing_silver_hair_0_4cd33d0e-135d-43c5-8236-225331cbdd40_0_q9hjik.jpg",
    category: "Mystical",
    tags: [
      "Pastel",
      "Celestial",
      "Stars",
      "Dreamlike",
      "Tranquil",
      "Beautiful",
      "Mystical",
      "SoftGlow",
      "AnimeWallpaper",
      "Ethereal",
    ],
    views: 231,
    downloads: 68,
    likes: [],
  },
  {
    title: "Web-Slinger in Action - The Amazing Spider-Man",
    description:
      "A thrilling close-up of Spider-Man mid-swing through the neon-lit city, his suit reflecting the glow of skyscrapers. Raindrops scatter as he propels forward, eyes locked on his next target, embodying speed, agility, and heroism.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354743/marvels-spider-man-1080x1920-11811_cycxcd.jpg",
    category: "Superhero",
    tags: [
      "SpiderMan",
      "PS5",
      "Marvel",
      "Superhero",
      "Action",
      "WebSwinging",
      "Cinematic",
      "Dynamic",
      "Epic",
      "AnimeWallpaper",
    ],
    views: 456,
    downloads: 167,
    likes: [],
  },
  {
    title: "Goku Ultra Instinct - Tranquil Power",
    description:
      "A mesmerizing close-up of Goku in his Ultra Instinct form, captured in a moment of absolute calm. His glowing silver hair and composed expression embody the balance between peace and strength, with soft cosmic energy swirling around him.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354154/Default_Closeup_of_Goku_in_his_Ultra_Instinct_form_silver_hair_0_a5891404-430b-421a-8e12-6c51c4d44da8_0_qgrhp6.jpg",
    category: "Fantasy",
    tags: [
      "Goku",
      "UltraInstinct",
      "DragonBall",
      "AnimeArt",
      "Serene",
      "DivinePower",
      "Saiyan",
      "Mystical",
      "Wallpaper",
      "Tranquil",
    ],
    views: 312,
    downloads: 102,
    likes: [],
  },
  {
    title: "Fated Connection - Under the Twilight Sky",
    description:
      "A breathtaking close-up of a girl gazing at the twilight sky, her eyes reflecting the fading sunlight. A soft breeze lifts her hair as distant shooting stars streak across the sky, evoking a sense of longing and destiny.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354156/Default_Closeup_of_a_melancholic_girl_with_flowing_silver_hair_1_3b3a4808-582b-442b-971d-b77edc58090e_0_qyls4o.jpg",
    category: "Romance",
    tags: [
      "YourName",
      "MakotoShinkai",
      "Twilight",
      "Dreamy",
      "Emotional",
      "Beautiful",
      "AnimeWallpaper",
      "Scenic",
      "Cinematic",
      "Melancholy",
    ],
    views: 378,
    downloads: 145,
    likes: [],
  },
  {
    title: "Tanjiro's Flame - Unyielding Spirit",
    description:
      "A fierce close-up of Tanjiro Kamado mid-battle, his eyes burning with determination. Fiery red flames swirl around his blade as he unleashes a powerful Hinokami Kagura strike, illuminating the night with its intensity.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354154/Default_Closeup_shot_of_a_fierce_anime_samurai_with_intense_ey_1_3711ecaf-2136-40df-8e73-84cdb809e515_0_fm4xo9.jpg",
    category: "Action",
    tags: [
      "Tanjiro",
      "DemonSlayer",
      "KimetsuNoYaiba",
      "HinokamiKagura",
      "Sword",
      "Flames",
      "Epic",
      "Battle",
      "AnimeWallpaper",
      "Cinematic",
    ],
    views: 189,
    downloads: 54,
    likes: [],
  },
  {
    title: "Neon Rebellion - Cyberpunk Dystopia",
    description:
      "A striking close-up of a lone cyberpunk warrior, eyes glowing with digital data, standing against a neon-lit cityscape. Rain drips down their sleek visor as holographic advertisements flicker in the background, capturing the raw energy of a futuristic rebellion.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354156/Default_Epic_cyberpunk_cityscape_at_night_neon_lights_glowing_3_f42de607-caf9-475b-8e69-55001f48bb43_0_l3sjtz.jpg",
    category: "Sci-Fi",
    tags: [
      "Cyberpunk",
      "Akira",
      "GhostInTheShell",
      "Dystopian",
      "NeonLights",
      "Futuristic",
      "AnimeWallpaper",
      "Dark",
      "HighTech",
      "Cinematic",
    ],
    views: 134,
    downloads: 47,
    likes: [],
  },
  {
    title: "Sunshine Girl - A Moment of Warmth",
    description:
      "A stunning close-up of a girl standing under the open sky, eyes closed as sunlight gently kisses her face. Raindrops sparkle around her, suspended in midair, blending warmth and melancholy in a magical, fleeting moment.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354156/Default_Closeup_of_a_serene_girl_with_long_flowing_pastelcolor_1_c8cd539e-8fd0-416a-b54d-9f456e94d4ad_0_mgqggy.jpg",
    category: "Fantasy",
    tags: [
      "WeatheringWithYou",
      "MakotoShinkai",
      "Sunlight",
      "Rain",
      "Ethereal",
      "Beautiful",
      "AnimeWallpaper",
      "Atmospheric",
      "Tranquil",
      "Cinematic",
    ],
    views: 287,
    downloads: 91,
    likes: [],
  },
  {
    title: "Nezuko's Serenity - Moonlit Beauty",
    description:
      "A peaceful close-up of Nezuko Kamado sitting under the soft glow of the full moon. Her gentle pink eyes reflect the night sky as cherry blossoms drift around her, capturing a moment of quiet elegance and mystery.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354154/Default_Closeup_shot_of_a_fierce_anime_samurai_with_intense_ey_0_d7c91732-fc16-4a9e-acb8-156faa4d7e90_0_up6rhw.jpg",
    category: "Fantasy",
    tags: [
      "Nezuko",
      "DemonSlayer",
      "KimetsuNoYaiba",
      "Serene",
      "Moonlight",
      "CherryBlossoms",
      "Tranquil",
      "Beautiful",
      "AnimeWallpaper",
      "Ethereal",
    ],
    views: 421,
    downloads: 123,
    likes: [],
  },
  {
    title: "Goku Ultra Instinct - The Calm Before the Storm",
    description:
      "A stunning close-up of Goku in his Ultra Instinct form, radiating divine energy. His silver hair glows as his piercing eyes exude both serenity and overwhelming power. Sparks of cosmic energy crackle around him, setting the stage for an epic battle.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354154/Default_Closeup_of_Goku_in_his_Ultra_Instinct_form_silver_hair_2_64515782-5c88-4747-99b4-89b7d2274380_0_tn9hoc.jpg",
    category: "Superpower",
    tags: [
      "Goku",
      "UltraInstinct",
      "DragonBall",
      "AnimeWallpaper",
      "Powerful",
      "Epic",
      "Saiyan",
      "Cosmic",
      "EnergyAura",
      "Cinematic",
    ],
    views: 256,
    downloads: 89,
    likes: [],
  },
  {
    title: "Whispers of the Wind - Pastel Serenity",
    description:
      "A delicate close-up of a serene girl with long, flowing pastel-colored hair, eyes closed as a gentle breeze lifts her strands. Soft cherry blossom petals drift around her, bathed in warm golden sunlight, creating a tranquil dreamlike atmosphere.",
    image:
      "https://res.cloudinary.com/dqw6dicdi/image/upload/v1743354154/Default_Closeup_of_a_serene_girl_with_long_flowing_pastelcolor_0_0464880b-d12f-42c6-ac03-c4d872f86d1e_0_rma8uw.jpg",
    category: "Fantasy",
    tags: [
      "Serene",
      "Pastel",
      "Dreamy",
      "Beautiful",
      "CherryBlossoms",
      "SoftLighting",
      "Tranquil",
      "Ethereal",
      "AnimeWallpaper",
      "Cinematic",
    ],
    views: 512,
    downloads: 178,
    likes: [],
  },
];
